name: deploy

on:
  push:
    branches:
      - 'trunk'

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install, Build and Deploy
        run: |
          npm install
          npm run deploy
